SELECT * FROM CLIENTE
SELECT * FROM DISTRITO

--SELECT * FROM CLIENTE
IF OBJECT_ID('SP_MANTENIMIENTOCLIENTE')IS NOT NULL 
	DROP PROC SP_MANTENIMIENTOCLIENTE
GO


CREATE PROC SP_MANTENIMIENTOCLIENTE(@IDE INT,@NOM VARCHAR(50),@MOV VARCHAR(15),
									@DIS INT,@COR VARCHAR(50))
AS
	MERGE INTO CLIENTE AS TARGET
	USING (SELECT @IDE,@NOM,@MOV,@DIS,@COR) AS SOURCE(IDE_CLI,NOM_CLI,MOV_CLI,IDE_DIS,COR_CLI)
	ON TARGET.IDE_CLI=SOURCE.IDE_CLI
	WHEN MATCHED THEN
		UPDATE SET TARGET.NOM_CLI=SOURCE.NOM_CLI,TARGET.MOV_CLI=SOURCE.MOV_CLI,
				   TARGET.IDE_DIS=SOURCE.IDE_DIS,TARGET.COR_CLI=SOURCE.COR_CLI
	WHEN NOT MATCHED THEN
		INSERT VALUES(SOURCE.NOM_CLI,SOURCE.MOV_CLI,SOURCE.IDE_DIS,SOURCE.COR_CLI);
GO




IF OBJECT_ID('SP_LISTARDISTRITO')IS NOT NULL 
	DROP PROC SP_LISTARDISTRITO
GO
CREATE PROC SP_LISTARDISTRITO
AS
	SELECT * FROM DISTRITO
GO




IF OBJECT_ID('SP_LISTACLIENTES')IS NOT NULL 
	DROP PROC SP_LISTACLIENTES
GO
CREATE PROC SP_LISTACLIENTES
AS
	SELECT C.IDE_CLI,C.NOM_CLI,C.MOV_CLI,P.DES_DIS,C.COR_CLI
		FROM CLIENTE C
		JOIN DISTRITO P ON C.IDE_DIS=P.IDE_DIS
GO




IF OBJECT_ID('SP_CLIENTES')IS NOT NULL 
	DROP PROC SP_CLIENTES
GO
CREATE PROC SP_CLIENTES
AS
	SELECT C.*
		FROM CLIENTE C
GO


IF OBJECT_ID('SP_ELIMINACLIENTE') IS NOT NULL 
	DROP PROC SP_ELIMINACLIENTE
GO
CREATE PROC SP_ELIMINACLIENTE(@IDE INT)
AS
	DELETE FROM CLIENTE WHERE IDE_CLI=@IDE
GO